### ISSUE TITLE
Images are not visible on webpage

### ISSUE THREAD

**Issue by HackerGwen** [HackerGwen/SJ-Guitars-HomePage#1]
Needed some help here. There is some problem with image path.

**Comment by Divyansh1315** [comment]
Hey I looked at your landing page. Can you please tell which image is not loading. As far as I can observe all the images are there.
Can you please elaborate your issue.
Thank you

**Comment by HackerGwen** [comment]
Thanks for helping. I thing there was some problem with image path. That time images were not loading but things are fixed now.

**Comment by Divyansh1315** [comment]
Wow that's great!!
